"""empty message

Revision ID: 2e84b21347e9
Revises: b21635949984
Create Date: 2019-10-31 13:11:49.723372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e84b21347e9'
down_revision = 'b21635949984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('f_status', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('f_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'f_status')
    op.drop_column('tour', 'f_status')
    # ### end Alembic commands ###
