"""empty message

Revision ID: 54234544e10e
Revises: 2e84b21347e9
Create Date: 2019-11-03 17:26:42.049036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54234544e10e'
down_revision = '2e84b21347e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_participant', sa.Column('tour_user_feedback', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_participant', 'tour_user_feedback')
    # ### end Alembic commands ###
