"""empty message

Revision ID: b21635949984
Revises: ba917cd1c46c
Create Date: 2019-10-31 12:50:54.547016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21635949984'
down_revision = 'ba917cd1c46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_participant', sa.Column('tour_user_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_participant', 'tour_user_rating')
    # ### end Alembic commands ###
