"""empty message

Revision ID: bc0f60f5481c
Revises: 91e24d2b270c
Create Date: 2019-10-30 12:17:59.424034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0f60f5481c'
down_revision = '91e24d2b270c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('ratings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ratings')
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
